#!/bin/bash
mkdir -p $HOME/.vim/ftplugin/tex
cp ftplugin/tex/*.vim $HOME/.vim/ftplugin/tex/
mkdir -p $HOME/.vim/doc
cp doc/*.txt $HOME/.vim/doc/
mkdir -p $HOME/bin
chmod a+x bin/*.sh
cp *.sh $HOME/bin/
